// next.config.js (Next.js 13+ con App Router)
import { Orbitron, Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";

export const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: "normal",
});

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
